version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdatabase
    ports:
      - "5435:5432"  # Map host port 5435 to container port 5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
  node:
    image: node:20
    container_name: node-app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3010:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdatabase
      - DB_PORT=5432
    depends_on:
      - postgres
    command: bash -c "npm install && npx prisma format && npx prisma migrate dev --name init && npx prisma migrate deploy && npx prisma generate && npm run dev"
volumes:
  postgres-data:
    driver: local
