-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE model (
--     id SERIAL PRIMARY KEY,
--     feature_id INT NOT NULL,
--     model_path VARCHAR(500) NOT NULL,
--     ddl_path VARCHAR(500) NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN KEY (feature_id) REFERENCES features(id) ON DELETE CASCADE
-- );
