-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TYPE application_status ADD VALUE IF NOT EXISTS 'Application Details';
-- ALTER TYPE application_status ADD VALUE IF NOT EXISTS 'Generate Schema';
-- ALTER TYPE application_status ADD VALUE IF NOT EXISTS 'Generate Endpoints';
-- ALTER TYPE application_status ADD VALUE IF NOT EXISTS 'Deployment';
