-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TYPE application_status AS ENUM ('active', 'inactive');
-- CREATE TYPE operations_method AS ENUM ('GET', 'POST', 'PUT', 'DELETE', 'PATCH');
--
-- CREATE TABLE applications (
--     id SERIAL PRIMARY KEY,
--     user_id UUID NOT NULL,
--     name VARCHAR(255) NOT NULL,
--     description TEXT,
--     status application_status DEFAULT 'active',
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
-- );
--
-- CREATE TABLE features (
--     id SERIAL PRIMARY KEY,
--     application_id INT NOT NULL,
--     name VARCHAR(255) NOT NULL,
--     description TEXT,
--     is_active BOOLEAN DEFAULT TRUE,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE
-- );
--
-- CREATE TABLE operations (
--     id SERIAL PRIMARY KEY,
--     feature_id INT NOT NULL,
--     route VARCHAR(255),
--     method operations_method NOT NULL,
--     is_authenticated BOOLEAN DEFAULT TRUE,
--     is_media BOOLEAN DEFAULT FALSE,
--     is_async BOOLEAN DEFAULT FALSE,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN KEY (feature_id) REFERENCES features(id) ON DELETE CASCADE
-- );
